### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by Archerious** [Genghis1227/guide_eap_proxy#1]
Thank you so much for this guide.

I have a a stupid question, will changing the DNS revolvers from AT&T affect ipv6 or the proxy? 

Based on my observium info (SNMP) it seems the AT&T DNS goes down a few times a week....

**Comment by Genghis1227** [comment]
Hey @Archerious,
Most definitely it will impact IPv6 since I was not able to really get it to work properly.

**Comment by Archerious** [comment]
What's the process to remove ipv6 and put DNS on Google?

My ipv6 isn't working as it is and I think changing the DNS resolvers will improve my connection since I get much higher ping when DNS is involved lately (110-140ms) on ethernet. If I just ping 8.8.8.8 I get usually around 8ms ping. Att dns isn't very good imo.

**Comment by Archerious** [comment]
![Screenshot_20191120-015905_Chrome](https://user-images.githubusercontent.com/26941475/69219871-6728f400-0b39-11ea-865e-0c0deef3db7c.jpg)
![Screenshot_20191120-015909_Chrome](https://user-images.githubusercontent.com/26941475/69219872-6728f400-0b39-11ea-8fb4-a75e695bd10b.jpg)

**Comment by Genghis1227** [comment]
You could try to follow the thread here to see if you want to get IPv6 enabled:  https://github.com/jaysoffian/eap_proxy/issues/3

To be honest I use the EdgeRouter basically to get me to the Internet.  I then put a Static IP in the Edgerouter for my Wifi Router.  From there I configure my DNS on my router to use whatever I want.  In my case, I have it going to my Pi-Hole that is configured to use Google DNS.  I put a secondary DNS as 8.8.8.8 so that if my Pi-Hole goes down I can still get DNS resolution.

The only thing about doing this is needing to forward the port in two places
- on the WiFi router to the device
- from the edge router to the WiFi router

**Comment by ann4belle** [comment]
Your IPv6 connection shouldn't be dependent on you using AT&T's DNS servers. I use Cloudflare's DoT resolver service and haven't had any issues.
